
version: '3'
services:
    node-app:
      environment:
        - DB_HOST=mongodb://mongo:27017/posts
      container_name: node-app
      image: benranson/webapp
      build: ./webapp
      ports:
        - "3000:3000"
      restart: on-failure
      depends_on:
        - mongo
    mongo:
      container_name: mongo
      image: benranson/mongod
      build: ./mongod
      volumes:
        - ./persistent_data:/data/db
      ports: 
        - "27017:27017"


